version: "3"

services:
  mariadb:
    image: mariadb
    volumes:
      - mariadb-storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  bench:
    image: anandology/frappe-bench:2021.10
    volumes:
      - .:/opt/frappe-bench/apps/lms
    environment:
      - FRAPPE_APPS=lms
      - FRAPPE_ALLOW_TESTS=true
      - FRAPPE_SITE_NAME=frappe.localhost
    depends_on:
      - mariadb
    ports:
      - 8000:8000
      - 9000:9000
volumes:
  mariadb-storage: {}
