name: Semantic Pull Request

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  # This workflow contains a single job called "build"
  semantic:
    name: Validate PR title
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: zeke/semantic-pull-requests@main
